project:
  type: website
  output-dir: docs

website:
  title: "Casagrande Institute for Higher Education Effectiveness"
  site-url: "https://casagrandeinstitute.github.io"
  navbar:
    logo: images/casagrande_institute_logo.png
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: false
